"""empty message

Revision ID: 43bebd7a51c5
Revises: 
Create Date: 2023-08-27 04:19:30.449375

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '43bebd7a51c5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), sa.Identity(always=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('uid_id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('nickname', sa.String(length=50), nullable=False),
    sa.Column('avatar', sa.String(length=256), nullable=False),
    sa.Column('wallpaper', sa.String(length=256), nullable=False),
    sa.Column('preview', sa.Text(), nullable=True),
    sa.Column('external_link', sa.String(length=256), nullable=False),
    sa.Column('continent', sa.Enum('europe', 'asia', 'africa', 'south_america', 'north_america', 'antarctica', 'australia', name='continents'), nullable=False),
    sa.Column('birthday', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('avatar'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('nickname'),
    sa.UniqueConstraint('uid_id'),
    sa.UniqueConstraint('wallpaper')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    # ### end Alembic commands ###
