"""empty message

Revision ID: 442878722fb4
Revises: 
Create Date: 2023-08-28 02:50:41.540868

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '442878722fb4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), sa.Identity(always=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('uid_id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('nickname', sa.String(length=50), nullable=False),
    sa.Column('avatar', sa.String(length=256), nullable=True),
    sa.Column('wallpaper', sa.String(length=256), nullable=True),
    sa.Column('preview', sa.Text(), nullable=True),
    sa.Column('external_link', sa.String(length=256), nullable=True),
    sa.Column('continent', sa.Enum('europe', 'asia', 'africa', 'south_america', 'north_america', 'antarctica', 'australia', name='continentsenum'), nullable=False),
    sa.Column('birthday', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('nickname'),
    sa.UniqueConstraint('uid_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    sa.Enum(name='continentsenum').drop(op.get_bind(), checkfirst=False)
    # ### end Alembic commands ###
