"""empty message

Revision ID: 52ae04cc2d0e
Revises: 6cd9cbd7701b
Create Date: 2023-09-08 02:22:30.172052

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '52ae04cc2d0e'
down_revision = '6cd9cbd7701b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tracks', schema=None) as batch_op:
        batch_op.alter_column('visibility',
               existing_type=postgresql.ENUM('all', 'registered', 'nobody', name='visibilitytypesenum'),
               type_=sa.Enum('all', 'registered', 'nobody', name='visibilityenum'),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tracks', schema=None) as batch_op:
        batch_op.alter_column('visibility',
               existing_type=sa.Enum('all', 'registered', 'nobody', name='visibilityenum'),
               type_=postgresql.ENUM('all', 'registered', 'nobody', name='visibilitytypesenum'),
               existing_nullable=False)

    # ### end Alembic commands ###
