"""empty message

Revision ID: 5dc55c804aef
Revises: 
Create Date: 2023-09-08 05:15:10.875986

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5dc55c804aef'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agreements',
    sa.Column('id', sa.Integer(), sa.Identity(always=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('agreement_name', sa.String(length=256), nullable=False),
    sa.Column('description', sa.String(length=512), nullable=True),
    sa.Column('icon_url', sa.String(length=256), nullable=False),
    sa.Column('agreement_text', sa.Text(), nullable=True),
    sa.Column('agreement_url', sa.String(length=256), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('music_styles',
    sa.Column('id', sa.Integer(), sa.Identity(always=False), nullable=False),
    sa.Column('style_name', sa.String(length=64), nullable=False),
    sa.Column('icon', sa.String(length=256), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('style_name')
    )
    op.create_table('operational_object_types',
    sa.Column('id', sa.Integer(), sa.Identity(always=False), nullable=False),
    sa.Column('type_name', sa.String(length=64), nullable=False),
    sa.Column('description', sa.String(length=1024), nullable=True),
    sa.Column('icon_url', sa.String(length=256), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('type_name')
    )
    op.create_table('user_types',
    sa.Column('id', sa.Integer(), sa.Identity(always=False), nullable=False),
    sa.Column('type_name', sa.String(length=32), nullable=False),
    sa.Column('description', sa.String(length=1024), nullable=True),
    sa.Column('icon', sa.String(length=256), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('type_name')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), sa.Identity(always=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('uid_id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('nickname', sa.String(length=50), nullable=False),
    sa.Column('avatar', sa.String(length=256), nullable=True),
    sa.Column('wallpaper', sa.String(length=256), nullable=True),
    sa.Column('preview', sa.Text(), nullable=True),
    sa.Column('external_link', sa.String(length=256), nullable=True),
    sa.Column('continent', sa.Enum('europe', 'asia', 'africa', 'south_america', 'north_america', 'antarctica', 'australia', name='continentsenum'), nullable=False),
    sa.Column('birthday', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('nickname'),
    sa.UniqueConstraint('uid_id')
    )
    op.create_table('operational_object_type_agreement_associations',
    sa.Column('id', sa.Integer(), sa.Identity(always=False), nullable=False),
    sa.Column('agreement_id', sa.Integer(), nullable=False),
    sa.Column('operational_object_type_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['agreement_id'], ['agreements.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['operational_object_type_id'], ['operational_object_types.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('tracks',
    sa.Column('id', sa.Integer(), sa.Identity(always=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('file_url', sa.String(length=512), nullable=False),
    sa.Column('wave_url', sa.String(length=512), nullable=False),
    sa.Column('title', sa.String(length=256), nullable=False),
    sa.Column('author', sa.String(length=256), nullable=False),
    sa.Column('cover', sa.Integer(), nullable=True),
    sa.Column('cover_url', sa.String(length=256), nullable=True),
    sa.Column('duration', sa.Integer(), nullable=False),
    sa.Column('style_id', sa.Integer(), nullable=False),
    sa.Column('checked', sa.Boolean(), nullable=False),
    sa.Column('visibility', sa.Enum('all', 'registered', 'nobody', name='visibilityenum'), nullable=False),
    sa.ForeignKeyConstraint(['style_id'], ['music_styles.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('title')
    )
    op.create_table('user_type_agreement_associations',
    sa.Column('id', sa.Integer(), sa.Identity(always=False), nullable=False),
    sa.Column('agreement_id', sa.Integer(), nullable=False),
    sa.Column('user_type_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['agreement_id'], ['agreements.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_type_id'], ['user_types.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('user_type_assignations',
    sa.Column('id', sa.Integer(), sa.Identity(always=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('type_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('canceled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('checked', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['type_id'], ['user_types.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('track_permissions',
    sa.Column('id', sa.Integer(), sa.Identity(always=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('track_id', sa.Integer(), nullable=False),
    sa.Column('agreement_id', sa.Integer(), nullable=False),
    sa.Column('canceled_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['agreement_id'], ['agreements.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['track_id'], ['tracks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('track_permission_track_associations',
    sa.Column('id', sa.Integer(), sa.Identity(always=False), nullable=False),
    sa.Column('track_permission_id', sa.Integer(), nullable=False),
    sa.Column('track_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['track_id'], ['tracks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['track_permission_id'], ['track_permissions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('track_permission_user_associations',
    sa.Column('id', sa.Integer(), sa.Identity(always=False), nullable=False),
    sa.Column('track_permission_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['track_permission_id'], ['track_permissions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('track_permission_user_type_associations',
    sa.Column('id', sa.Integer(), sa.Identity(always=False), nullable=False),
    sa.Column('track_permission_id', sa.Integer(), nullable=False),
    sa.Column('user_types_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['track_permission_id'], ['track_permissions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_types_id'], ['user_types.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('track_permission_user_type_associations')
    op.drop_table('track_permission_user_associations')
    op.drop_table('track_permission_track_associations')
    op.drop_table('track_permissions')
    op.drop_table('user_type_assignations')
    op.drop_table('user_type_agreement_associations')
    op.drop_table('tracks')
    op.drop_table('operational_object_type_agreement_associations')
    op.drop_table('users')
    op.drop_table('user_types')
    op.drop_table('operational_object_types')
    op.drop_table('music_styles')
    op.drop_table('agreements')
    # ### end Alembic commands ###
