"""empty message

Revision ID: 6cf954b8edca
Revises: f8bdce461c82
Create Date: 2023-09-09 03:47:46.617369

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6cf954b8edca'
down_revision = 'f8bdce461c82'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tracks', schema=None) as batch_op:
        batch_op.drop_constraint('tracks_title_key', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tracks', schema=None) as batch_op:
        batch_op.create_unique_constraint('tracks_title_key', ['title'])

    # ### end Alembic commands ###
