"""empty message

Revision ID: 8ae8ffc0a520
Revises: ced04ebcbf83
Create Date: 2023-09-02 21:48:52.483335

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8ae8ffc0a520'
down_revision = 'ced04ebcbf83'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('music_styles',
    sa.Column('id', sa.Integer(), sa.Identity(always=False), nullable=False),
    sa.Column('style_name', sa.String(length=64), nullable=False),
    sa.Column('icon', sa.String(length=256), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('style_name')
    )
    op.create_table('tracks',
    sa.Column('id', sa.Integer(), sa.Identity(always=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('file_url', sa.String(length=512), nullable=False),
    sa.Column('wave_url', sa.String(length=512), nullable=False),
    sa.Column('title', sa.String(length=256), nullable=False),
    sa.Column('author', sa.String(length=256), nullable=False),
    sa.Column('cover', sa.Integer(), nullable=True),
    sa.Column('cover_url', sa.String(length=256), nullable=True),
    sa.Column('duration', sa.Integer(), nullable=False),
    sa.Column('style_id', sa.Integer(), nullable=False),
    sa.Column('checked', sa.Boolean(), nullable=False),
    sa.Column('visibility', sa.Enum('all', 'registered', 'nobody', name='visibilitytypesenum'), nullable=False),
    sa.ForeignKeyConstraint(['style_id'], ['music_styles.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('title')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tracks')
    op.drop_table('music_styles')
    # ### end Alembic commands ###
