"""empty message

Revision ID: 8bc9ef0eddaf
Revises: 792d09268eb2
Create Date: 2023-09-03 00:03:05.785960

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8bc9ef0eddaf'
down_revision = '792d09268eb2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('track_permission_assignations', schema=None) as batch_op:
        batch_op.drop_constraint('track_permission_assignations_user_type_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('track_permission_assignations_agreement_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('track_permission_assignations_user_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('track_permission_assignations_track_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'agreements', ['agreement_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'user_types', ['user_type_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'tracks', ['track_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('track_permission_assignations', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('track_permission_assignations_track_id_fkey', 'tracks', ['track_id'], ['id'])
        batch_op.create_foreign_key('track_permission_assignations_user_id_fkey', 'users', ['user_id'], ['id'])
        batch_op.create_foreign_key('track_permission_assignations_agreement_id_fkey', 'agreements', ['agreement_id'], ['id'])
        batch_op.create_foreign_key('track_permission_assignations_user_type_id_fkey', 'user_types', ['user_type_id'], ['id'])

    # ### end Alembic commands ###
