"""empty message

Revision ID: 96e8d5bcd547
Revises: 8bc9ef0eddaf
Create Date: 2023-09-07 00:28:48.992450

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '96e8d5bcd547'
down_revision = '8bc9ef0eddaf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('operational_object_type_agreement_associations',
    sa.Column('id', sa.Integer(), sa.Identity(always=False), nullable=False),
    sa.Column('agreement_id', sa.Integer(), nullable=False),
    sa.Column('operational_object_type_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['agreement_id'], ['agreements.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['operational_object_type_id'], ['operational_object_types.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('user_type_agreement_associations',
    sa.Column('id', sa.Integer(), sa.Identity(always=False), nullable=False),
    sa.Column('agreement_id', sa.Integer(), nullable=False),
    sa.Column('user_type_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['agreement_id'], ['agreements.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_type_id'], ['user_types.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('track_permissions',
    sa.Column('id', sa.Integer(), sa.Identity(always=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('track_id', sa.Integer(), nullable=False),
    sa.Column('agreement_id', sa.Integer(), nullable=False),
    sa.Column('canceled_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['agreement_id'], ['agreements.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['track_id'], ['tracks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('track_permission_track_associations',
    sa.Column('id', sa.Integer(), sa.Identity(always=False), nullable=False),
    sa.Column('track_permission_id', sa.Integer(), nullable=False),
    sa.Column('track_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['track_id'], ['tracks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['track_permission_id'], ['track_permissions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('track_permission_user_associations',
    sa.Column('id', sa.Integer(), sa.Identity(always=False), nullable=False),
    sa.Column('track_permission_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['track_permission_id'], ['track_permissions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('track_permission_user_type_associations',
    sa.Column('id', sa.Integer(), sa.Identity(always=False), nullable=False),
    sa.Column('track_permission_id', sa.Integer(), nullable=False),
    sa.Column('user_types_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['track_permission_id'], ['track_permissions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_types_id'], ['user_types.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.drop_table('operational_object_types_agreements_associations')
    op.drop_table('user_types_agreements_associations')
    op.drop_table('track_permission_assignations')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('track_permission_assignations',
    sa.Column('id', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1), autoincrement=True, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('track_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('agreement_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('user_type_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('canceled_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['agreement_id'], ['agreements.id'], name='track_permission_assignations_agreement_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['track_id'], ['tracks.id'], name='track_permission_assignations_track_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='track_permission_assignations_user_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_type_id'], ['user_types.id'], name='track_permission_assignations_user_type_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='track_permission_assignations_pkey'),
    sa.UniqueConstraint('id', name='track_permission_assignations_id_key')
    )
    op.create_table('user_types_agreements_associations',
    sa.Column('id', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1), autoincrement=True, nullable=False),
    sa.Column('agreement_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('user_type_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['agreement_id'], ['agreements.id'], name='user_types_agreements_associations_agreement_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_type_id'], ['user_types.id'], name='user_types_agreements_associations_user_type_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='user_types_agreements_associations_pkey'),
    sa.UniqueConstraint('id', name='user_types_agreements_associations_id_key')
    )
    op.create_table('operational_object_types_agreements_associations',
    sa.Column('id', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1), autoincrement=True, nullable=False),
    sa.Column('agreement_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('operational_object_type_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['agreement_id'], ['agreements.id'], name='operational_object_types_agreements_associati_agreement_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['operational_object_type_id'], ['operational_object_types.id'], name='operational_object_types_agreem_operational_object_type_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='operational_object_types_agreements_associations_pkey'),
    sa.UniqueConstraint('id', name='operational_object_types_agreements_associations_id_key')
    )
    op.drop_table('track_permission_user_type_associations')
    op.drop_table('track_permission_user_associations')
    op.drop_table('track_permission_track_associations')
    op.drop_table('track_permissions')
    op.drop_table('user_type_agreement_associations')
    op.drop_table('operational_object_type_agreement_associations')
    # ### end Alembic commands ###
