"""empty message

Revision ID: 9d3c78540317
Revises: 7769c8cd7b0c
Create Date: 2023-08-31 08:06:36.281672

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9d3c78540317'
down_revision = '7769c8cd7b0c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_type_assignations', schema=None) as batch_op:
        batch_op.alter_column('type_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_constraint('user_type_assignations_type_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'user_types', ['type_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_type_assignations', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('user_type_assignations_type_id_fkey', 'user_types', ['type_id'], ['id'])
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('type_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
